name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Checkout specific version of JacoDB
        uses: actions/checkout@v4
        with:
          repository: UnitTestBot/jacodb
          ref: lipen/sarif4k
          path: jacodb

      - name: Build JacoDB
        working-directory: jacodb
        run: ./gradlew publishToMavenLocal

      - name: Build and run tests
        run: ./gradlew build --stacktrace --scan

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/build/test-results/**/*.xml"
