name: Demo With USVM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run analysis on sample project
        working-directory: examples/byteflow-plugin-usage
        run: ../../gradlew runAnalyzer -PuseUsvmAnalysis=true

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: examples/byteflow-plugin-usage/report.sarif
          category: demo-with-usvm

      - name: Upload SARIF report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sarif-report
          path: examples/byteflow-plugin-usage/report.sarif
